
package com.example.checkin;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CheckInPortType", targetNamespace = "http://example.com/checkin")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CheckInPortType {


    /**
     * 
     * @param checkInSearch
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:studentCheckIn")
    @WebResult(name = "result", targetNamespace = "http://example.com/checkin", partName = "result")
    public String studentCheckIn(
        @WebParam(name = "checkInSearch", targetNamespace = "http://example.com/checkin", partName = "checkInSearch")
        CheckInSearch checkInSearch);

}
