
package com.example.checkin;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CheckInService", targetNamespace = "http://example.com/checkin", wsdlLocation = "file:/E:/Alearn/SOE_hw/assignment2/src/main/java/wsdl/CheckInService.wsdl")
public class CheckInService
    extends Service
{

    private final static URL CHECKINSERVICE_WSDL_LOCATION;
    private final static WebServiceException CHECKINSERVICE_EXCEPTION;
    private final static QName CHECKINSERVICE_QNAME = new QName("http://example.com/checkin", "CheckInService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/E:/Alearn/SOE_hw/assignment2/src/main/java/wsdl/CheckInService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CHECKINSERVICE_WSDL_LOCATION = url;
        CHECKINSERVICE_EXCEPTION = e;
    }

    public CheckInService() {
        super(__getWsdlLocation(), CHECKINSERVICE_QNAME);
    }

    public CheckInService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CHECKINSERVICE_QNAME, features);
    }

    public CheckInService(URL wsdlLocation) {
        super(wsdlLocation, CHECKINSERVICE_QNAME);
    }

    public CheckInService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CHECKINSERVICE_QNAME, features);
    }

    public CheckInService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CheckInService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CheckInPortType
     */
    @WebEndpoint(name = "CheckInPort")
    public CheckInPortType getCheckInPort() {
        return super.getPort(new QName("http://example.com/checkin", "CheckInPort"), CheckInPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CheckInPortType
     */
    @WebEndpoint(name = "CheckInPort")
    public CheckInPortType getCheckInPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://example.com/checkin", "CheckInPort"), CheckInPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CHECKINSERVICE_EXCEPTION!= null) {
            throw CHECKINSERVICE_EXCEPTION;
        }
        return CHECKINSERVICE_WSDL_LOCATION;
    }

}
