
package com.example.archive;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StudentInfoPortType", targetNamespace = "http://example.com/archive")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StudentInfoPortType {


    /**
     * 
     * @param studentInfoSearch
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "getStudentInfo")
    @WebResult(name = "studentInfo", targetNamespace = "http://example.com/archive", partName = "studentInfo")
    public String getStudentInfo(
        @WebParam(name = "studentInfoSearch", targetNamespace = "http://example.com/archive", partName = "studentInfoSearch")
        StudentInfoSearch studentInfoSearch);

}
