
package com.example.authenticate;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AuthenticationPortType", targetNamespace = "http://example.com/authenticate")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AuthenticationPortType {


    /**
     * 
     * @param credentials
     * @return
     *     returns boolean
     */
    @WebMethod(action = "authenticate")
    @WebResult(name = "token", targetNamespace = "http://example.com/authenticate", partName = "token")
    public boolean authenticate(
        @WebParam(name = "Credentials", targetNamespace = "http://example.com/authenticate", partName = "Credentials")
        Credentials credentials);

}
